"""Add description status due_date

Revision ID: 024d7d598d0d
Revises: 
Create Date: 2026-01-07 19:49:19.006112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '024d7d598d0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('todo', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.add_column('todo', sa.Column('due_date', sa.DateTime(), nullable=True))
    # Create enum type first if it doesn't exist
    # todo_status = sa.Enum('PENDING', 'COMPLETED', name='todostatus')
    # todo_status.create(op.get_bind(), checkfirst=True)
    # op.add_column('todo', sa.Column('status', todo_status, nullable=False, server_default='PENDING'))
    # op.add_column('todo', sa.Column('updated_at', sa.DateTime(), nullable=True))
    class TodoBase(TimestampModel):
    title: str = Field(max_length=255)
    description: Optional[str] = Field(default=None)
    due_date: Optional[datetime] = Field(default=None)
    status: str = Field(default="pending") # Changed to str to avoid DB Enum mismatch
    is_completed: bool = Field(default=False)

class Todo(TodoBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: str = Field(index=True)

class TodoCreate(TodoBase):
    pass # status is str, defaults to "pending"

class TodoRead(TodoBase):
    id: int
    user_id: str

class TodoUpdate(SQLModel):
    title: Optional[str] = None
    description: Optional[str] = None
    due_date: Optional[datetime] = None
    status: Optional[str] = None
    is_completed: Optional[bool] = None

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'status')
    op.drop_column('todo', 'due_date')
    op.drop_column('todo', 'description')
    op.drop_table('user')
    # ### end Alembic commands ###
